services:
  - type: web
    name: shopflow
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 9090
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
